POST http://localhost:9090/register
Content-Type: application/json

{
    "username":"testuser",
    "email":"testuser@example.com",
    "password":"testpassword",
    "name":"Test User"
}

###

POST http://localhost:9090/login
Content-Type: application/json

{
    "email":"testuser@example.com",
    "password":"testpassword"
}

###

POST http://localhost:9090/update_profile_data
Content-Type: application/json

{
    "token":"765c99d1969beede3c07883ae240f8b6c8bdaf94c8587cc7a302a59ae99f3b0e",
    "bio":"I am Neha",
    "currentPost":"Software Engineer",
    "pastWork":[
        {
            "company":"Google",
            "position":"Software Engineer",
            "years":"2023-Present"
        }
    ],
    "education":[
        {
            "school":"ABC University",
            "degree":"B.Tech",
            "fieldOfStudy":"Computer Science"
        }
    ]
}

###

POST http://localhost:9090/get_user_and_profile HTTP/1.1
content-Type: application/json

{
    "token": "765c99d1969beede3c07883ae240f8b6c8bdaf94c8587cc7a302a59ae99f3b0e"
}

###

GET http://localhost:9090/user/get_all_users HTTP/1.1
